name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the Latest Package Code
        uses: actions/checkout@v3
      - name: Setup Pulsar Editor
        uses: pulsar-edit/action-pulsar-dependency@s985-update-win-path-registration
      - name: Install dependencies (Windows)
        if: ${{ runner.os == 'Windows' }}
        # Currently the Pulsar process starts, but unlike *nix doesn't wait for ppm to finish, probably because pulsar.cmd needs updated
        # So we'll fallback to ppm (still named apm) instead
        run: apm install
      - name: Install dependencies (*nix)
        if: ${{ runner.os != 'Windows' }}
        run: pulsar --package install
      - name: Run the headless Pulsar Tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: pulsar --test spec
          # working-directory: ./pulsar
